// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  securitySidebar: [{ type: 'autogenerated', dirName: 'security' }],
  writeupsSidebar: [{ type: 'autogenerated', dirName: 'writeups' }],
}

module.exports = sidebars
