// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  securitySidebar: [{ type: 'autogenerated', dirName: 'security' }],
  universitySidebar: [{ type: 'autogenerated', dirName: 'university' }],
}

module.exports = sidebars
